### ISSUE TITLE
getTotal and getCompleted no.s dont matching during System Testing is stopped and restarted multiple times

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-core#500]
I'm Running the System test for .net (easily reproducible for other platforms). Where I kill the test system after few iterations and then start with resume option(it tries to run system test with existing docs and cluster). After few such kill and restart, I'm seeing that getTotal and getCompleted no.s are not matching once the replication becomes IDLE.

Here is the snippet of logs after the doc insertion options finished
```
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "idle"
Got response: L58407328
Got response: L58402637
Exception in thread Thread-196:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/mobile-testkit/testsuites/CBLTester/System_test_multiple_device/test_system_testing.py", line 275, in _replicaton_status_check
    assert total == completed, "total is not equal to completed"
AssertionError: total is not equal to completed
assert 58407328L == 58402637L

Got response: L746798
Doc count is - set([746798L])
```

Here is the project to reproduce the scenario -

https://github.com/couchbaselabs/mobile-testkit/tree/feature/cbl20-ver1/CBLClient/Apps

Below is the repo command to start the system test.  Below command will set the cluster and start the test. It will also take some time to get the iterations started depending on the no. of docs to start with.

```
pytest -rsx -s --mode=cc --server-version=5.5.0-2368 --sync-gateway-version=2.0.0-832 --liteserv-platforms=dotnet --liteserv-versions
=2.0.0-713 --liteserv-hosts=localhost --liteserv-port=8080 --xattrs --create-db-per-suite="suite_db"  --timeout=832000   --no-db-delete  -k test_system testsuites/CBLTester
/System_test_multiple_device/test_system_testing.py --skip-provisioning
```

After killing the test after few iterations, one can resume the test using below command - 
```
pytest -rsx -s --mode=cc --server-version=5.5.0-2368 --sync-gateway-version=2.0.0-832 --liteserv-platforms=dotnet --liteserv-versions
=2.0.0-703 --liteserv-hosts=172.23.121.73 --liteserv-port=8080 --xattrs --create-db-per-suite="suite_db"  --timeout=832000   --no-db-delete  -k test_system testsuites/CBLTester
/System_test_multiple_device/test_system_testing.py --skip-provisioning  --resume-cluster
```

P.S. - This issue happens only when I stop and resume the test bunch of times. For an uninterrupted run, I don't this issue.

**Comment by raghusarangapani** [comment]
I was able to reproduce the issue with 500 docs using the second parametrized variable set `(500, 5, 10, 5, 10, 10, 1 * 20)` and with just one kill.

Test log
```
Updating 10 docs on suite_db_1 db - [u'cbl_suite_db_1_336', u'cbl_suite_db_1_469', u'cbl_suite_db_1_201', u'cbl_suite_db_1_115', u'cbl_suite_db_1_481', u'cbl_suite_db_1_219', u'cbl_suite_db_1_164', u'cbl_suite_db_1_237', u'cbl_suite_db_1_392', u'cbl_suite_db_1_101']
updating bulk docs
Got response: I-1
Got response: I-1
Got response: I-1
Got response: I-1
Got response: I-1
Got response: "busy"
Activity level: busy
Got response: I-1
Got response: "idle"
Got response: L15532
Got response: L15527
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/raghu.sarangapani/code/mobile-testkit/testsuites/CBLTester/System_test_multiple_device/test_system_testing.py", line 275, in _replicaton_status_check
    assert total == completed, "total is not equal to completed"
AssertionError: total is not equal to completed
assert 15532L == 15527L
```
Corresponding CBL logs:
```
VERBOSE) Sync {Repl#86} progress +1/+0, 1 docs -- now 15535 / 15542, 134 docs
INFO) Sync {Repl#86} activityLevel=busy: connectionState=2
INFO) Sync {Repl#86} pushStatus=idle, pullStatus=busy, dbStatus=idle, progress=15536/15542
VERBOSE) Sync {Repl#86} progress +1/+0, 1 docs -- now 15536 / 15542, 135 docs
INFO) Sync {Repl#86} activityLevel=busy: connectionState=2
INFO) Sync {Repl#86} pushStatus=idle, pullStatus=busy, dbStatus=idle, progress=15537/15542
VERBOSE) Sync {Repl#86} progress +1/+0, 1 docs -- now 15537 / 15542, 136 docs
INFO) Sync {Repl#86} activityLevel=busy: connectionState=2
INFO) Sync {Repl#86} pushStatus=idle, pullStatus=idle, dbStatus=idle, progress=15537/15542
INFO) Sync {Repl#86} activityLevel=idle: connectionState=2
INFO) Sync {Repl#86} now idle
INFO) Sync {Repl#86} activityLevel=idle: connectionState=2
```

Full CBL logs:
https://gist.github.com/raghusarangapani/8bddd32a4e92f9b7fa2b38638b7da56e

**Comment by borrrden** [comment]
Migrated to [CBL-55](https://issues.couchbase.com/browse/CBL-55)
